# Generated by Django 4.2.11 on 2024-04-25 14:58

from dbview.helpers import CreateView

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW public.expandedassets AS
            SELECT assets.id,
            assets.url,
            assets.name,
            assets.owner,
            users.displayname AS ownername,
            users.url AS ownerurl,
            assets.formats,
            assets.description,
            assets.visibility,
            assets.curated,
            assets.polyid,
            assets.polydata,
            assets.thumbnail
            FROM (public.assets
            LEFT JOIN public.users ON ((assets.owner = users.id)));
            """,
            reverse_sql="""
            DROP VIEW IF EXISTS public.expandedassets;
            """,
        ),
    ]
