# Generated by Django 5.0.6 on 2024-06-12 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='color_space',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='likes',
            field=models.ManyToManyField(to='api.user'),
        ),
        migrations.AddField(
            model_name='asset',
            name='orienting_rotation',
            field=models.JSONField(default='[0,0,0,0]'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayname',
            field=models.CharField(max_length=50, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(max_length=255, verbose_name='User Name / URL'),
        ),
    ]
