# Generated by Django 5.0.6 on 2024-05-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_asset_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicecode',
            old_name='device_code',
            new_name='devicecode',
        ),
    ]
