# Generated by Django 5.0.6 on 2024-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_asset_color_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='api.user'),
        ),
    ]
