ORIGINAL_OBJ_FORMAT = 1
TILT_FORMAT = 2
UNKNOWN_GLTF_FORMAT_A = 4
ORIGINAL_FBX_FORMAT = 6
BLOCKS_FORMAT = 7
USD_FORMAT = 8
HTML_FORMAT = 11
ORIGINAL_GLTF_FORMAT = 12
TOUR_CREATOR_EXPERIENCE = 13
JSON_FORMAT = 15
LULLMODEL_FORMAT = 16
SAND_FORMAT_A = 17
GLB_FORMAT = 18
SAND_FORMAT_B = 19
SANDC_FORMAT = 20
PB_FORMAT = 21
UNKNOWN_GLTF_FORMAT_B = 22
ORIGINAL_TRIANGULATED_OBJ_FORMAT = 24
JPG_BUGGY = 25
USDZ_FORMAT = 26
UPDATED_GLTF_FORMAT = 30
EDITOR_SETTINGS_PB_FORMAT = 32
UNKNOWN_GLTF_FORMAT_C = 35
UNKNOWN_GLB_FORMAT_A = 36
UNKNOWN_GLB_FORMAT_B = 38
POLYGONE_TILT_FORMAT = 1000
POLYGONE_BLOCKS_FORMAT = 1001
POLYGONE_GLB_FORMAT = 1002
POLYGONE_GLTF_FORMAT = 1003
POLYGONE_OBJ_FORMAT = 1004
POLYGONE_FBX_FORMAT = 1005

role_display {
     1: "ORIGINAL_OBJ_FORMAT",
     2: "TILT_FORMAT",
     4: "UNKNOWN_GLTF_FORMAT_A",
     6: "ORIGINAL_FBX_FORMAT",
     7: "BLOCKS_FORMAT",
     8: "USD_FORMAT",
     11: "HTML_FORMAT",
     12: "ORIGINAL_GLTF_FORMAT",
     13: "TOUR_CREATOR_EXPERIENCE",
     15: "JSON_FORMAT",
     16: "LULLMODEL_FORMAT",
     17: "SAND_FORMAT_A",
     18: "GLB_FORMAT",
     19: "SAND_FORMAT_B",
     20: "SANDC_FORMAT",
     21: "PB_FORMAT",
     22: "UNKNOWN_GLTF_FORMAT_B",
     24: "ORIGINAL_TRIANGULATED_OBJ_FORMAT",
     25: "JPG_BUGGY",
     26: "USDZ_FORMAT",
     30: "UPDATED_GLTF_FORMAT",
     32: "EDITOR_SETTINGS_PB_FORMAT",
     35: "UNKNOWN_GLTF_FORMAT_C",
     36: "UNKNOWN_GLB_FORMAT_A",
     38: "UNKNOWN_GLB_FORMAT_B",
     1000: "POLYGONE_TILT_FORMAT",
     1001: "POLYGONE_BLOCKS_FORMAT",
     1002: "POLYGONE_GLB_FORMAT",
     1003: "POLYGONE_GLTF_FORMAT",
     1004: "POLYGONE_OBJ_FORMAT",
     1005: "POLYGONE_FBX_FORMAT",
}

EXTENSION_ROLE_MAP = {
    ".tilt": 1000,
    ".blocks": 1001,
    ".glb": 1002,
    ".gltf": 1003,
    ".obj": 1004,
    ".fbx": 1005,
}
