ORIGINAL_OBJ_FORMAT = 1
TILT_FORMAT = 2
UNKNOWN_GLTF_FORMAT_A = 4
ORIGINAL_FBX_FORMAT = 6
BLOCKS_FORMAT = 7
USD_FORMAT = 8
HTML_FORMAT = 11
ORIGINAL_GLTF_FORMAT = 12
TOUR_CREATOR_EXPERIENCE = 13
JSON_FORMAT = 15
LULLMODEL_FORMAT = 16
SAND_FORMAT_A = 17
GLB_FORMAT = 18
SAND_FORMAT_B = 19
SANDC_FORMAT = 20
PB_FORMAT = 21
UNKNOWN_GLTF_FORMAT_B = 22
ORIGINAL_TRIANGULATED_OBJ_FORMAT = 24
JPG_BUGGY = 25
USDZ_FORMAT = 26
UPDATED_GLTF_FORMAT = 30
EDITOR_SETTINGS_PB_FORMAT = 32
UNKNOWN_GLTF_FORMAT_C = 35
UNKNOWN_GLB_FORMAT_A = 36
UNKNOWN_GLB_FORMAT_B = 38
TILT_NATIVE_GLTF = 39
USER_SUPPLIED_GLTF = 40
POLYGONE_TILT_FORMAT = 1000
POLYGONE_BLOCKS_FORMAT = 1001
POLYGONE_GLB_FORMAT = 1002
POLYGONE_GLTF_FORMAT = 1003
POLYGONE_OBJ_FORMAT = 1004
POLYGONE_FBX_FORMAT = 1005

role_display = {
    1: "ORIGINAL_OBJ_FORMAT",
    2: "TILT_FORMAT",
    4: "UNKNOWN_GLTF_FORMAT_A",
    6: "ORIGINAL_FBX_FORMAT",
    7: "BLOCKS_FORMAT",
    8: "USD_FORMAT",
    11: "HTML_FORMAT",
    12: "ORIGINAL_GLTF_FORMAT",
    13: "TOUR_CREATOR_EXPERIENCE",
    15: "JSON_FORMAT",
    16: "LULLMODEL_FORMAT",
    17: "SAND_FORMAT_A",
    18: "GLB_FORMAT",
    19: "SAND_FORMAT_B",
    20: "SANDC_FORMAT",
    21: "PB_FORMAT",
    22: "UNKNOWN_GLTF_FORMAT_B",
    24: "ORIGINAL_TRIANGULATED_OBJ_FORMAT",
    25: "JPG_BUGGY",
    26: "USDZ_FORMAT",
    30: "UPDATED_GLTF_FORMAT",
    32: "EDITOR_SETTINGS_PB_FORMAT",
    35: "UNKNOWN_GLTF_FORMAT_C",
    36: "UNKNOWN_GLB_FORMAT_A",
    38: "UNKNOWN_GLB_FORMAT_B",
    39: "TILT_NATIVE_GLTF",
    40: "USER_SUPPLIED_GLTF",
    1000: "POLYGONE_TILT_FORMAT",
    1001: "POLYGONE_BLOCKS_FORMAT",
    1002: "POLYGONE_GLB_FORMAT",
    1003: "POLYGONE_GLTF_FORMAT",
    1004: "POLYGONE_OBJ_FORMAT",
    1005: "POLYGONE_FBX_FORMAT",
}

ROLE_STR_TO_INT = {v: k for k, v in role_display.items()}

EXTENSION_ROLE_MAP = {
    ".tilt": 1000,
    ".blocks": 1001,
    ".glb": 1002,
    ".gltf": 1003,
    ".obj": 1004,
    ".fbx": 1005,
}
FORMAT_ROLE_CHOICES = [(k, v) for k, v in role_display.items()]

PRETTY_FORMATS = {
    "ORIGINAL_OBJ_FORMAT": "obj",
    "TILT_FORMAT": "tilt",
    "UNKNOWN_GLTF_FORMAT_A": "unknown gltf a",
    "ORIGINAL_FBX_FORMAT": "original fbx",
    "BLOCKS_FORMAT": "blocks",
    "USD_FORMAT": "usd",
    "HTML_FORMAT": "html",
    "ORIGINAL_GLTF_FORMAT": "original gltf",
    "TOUR_CREATOR_EXPERIENCE": "tour creator experience",
    "JSON_FORMAT": "json",
    "LULLMODEL_FORMAT": "lullmodel",
    "SAND_FORMAT_A": "sand a",
    "GLB_FORMAT": "glb",
    "SAND_FORMAT_B": "sand b",
    "SANDC_FORMAT": "sandc",
    "PB_FORMAT": "pb",
    "UNKNOWN_GLTF_FORMAT_B": "unknown gltf b",
    "ORIGINAL_TRIANGULATED_OBJ_FORMAT": "triangulated obj",
    "JPG_BUGGY": "jpg buggy",
    "USDZ_FORMAT": "usdz",
    "UPDATED_GLTF_FORMAT": "gltf",
    "EDITOR_SETTINGS_PB_FORMAT": "editor settings pb",
    "UNKNOWN_GLTF_FORMAT_C": "unknown gltf c",
    "UNKNOWN_GLB_FORMAT_A": "unknown glb a",
    "UNKNOWN_GLB_FORMAT_B": "unknown glb b",
    "TILT_NATIVE_GLTF": "tilt native gltf",
    "USER_SUPPLIED_GLTF": "user supplied gltf",
    "POLYGONE_TILT_FORMAT": "polygone tilt",
    "POLYGONE_BLOCKS_FORMAT": "polygone blocks",
    "POLYGONE_GLB_FORMAT": "polygone glb",
    "POLYGONE_GLTF_FORMAT": "polygone gltf",
    "POLYGONE_OBJ_FORMAT": "polygone obj",
    "POLYGONE_FBX_FORMAT": "polygone fbx",
}
