# Generated by Django 5.0.6 on 2024-06-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icosa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="migrated",
            field=models.BooleanField(default=False),
        ),
    ]
