# Generated by Django 5.0.6 on 2025-03-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0003_copy_from_asset_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetowner',
            name='likes',
        ),
        migrations.DeleteModel(
            name='OwnerAssetLike',
        ),
    ]
