# Generated by Django 5.0.6 on 2025-03-15 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0004_remove_assetowner_likes_delete_ownerassetlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetowner',
            name='password',
        ),
        migrations.AlterField(
            model_name='devicecode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
