# Generated by Django 5.0.6 on 2025-03-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0005_remove_assetowner_password_alter_devicecode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetowner',
            name='access_token',
        ),
    ]
