# Generated by Django 5.0.6 on 2024-06-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0006_alter_asset_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='icosa.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icosa.user'),
        ),
    ]
