# Generated by Django 5.0.6 on 2025-04-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0007_userapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
    ]
