# Generated by Django 5.0.6 on 2024-06-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0007_remove_asset_likes_user_likes_alter_asset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted')], db_default='PRIVATE', default='PRIVATE', max_length=255),
        ),
    ]
