# Generated by Django 5.0.6 on 2024-06-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icosa", "0008_alter_asset_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAssetLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_liked", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icosa.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icosa.user",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="likes",
        ),
        migrations.AddField(
            model_name="user",
            name="likes",
            field=models.ManyToManyField(
                blank=True, through="icosa.UserAssetLike", to="icosa.asset"
            ),
        ),
    ]
