# Generated by Django 5.0.6 on 2025-04-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0008_remove_user_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAPIKey',
        ),
    ]
