# Generated by Django 5.1.8 on 2025-04-16 13:37

import django.core.validators
import icosa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0009_delete_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='preview_image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=icosa.models.preview_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=icosa.models.thumbnail_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='mastheadsection',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=icosa.models.masthead_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
