# Generated by Django 5.0.6 on 2024-06-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0009_userassetlike_alter_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='User Name / URL'),
        ),
    ]
