# Generated by Django 5.1.8 on 2025-04-23 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0010_alter_asset_preview_image_alter_asset_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='last_reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
