# Generated by Django 5.1.8 on 2025-06-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0011_alter_asset_last_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='license',
            field=models.CharField(blank=True, choices=[('', 'No license chosen'), ('CREATIVE_COMMONS_BY_3_0', 'CC BY Attribution 3.0 International'), ('CREATIVE_COMMONS_BY_ND_3_0', 'CC BY-ND Attribution-NoDerivatives 3.0 International'), ('CREATIVE_COMMONS_BY_4_0', 'CC BY Attribution 4.0 International'), ('CREATIVE_COMMONS_0', 'CC0 1.0 Universal'), ('ALL_RIGHTS_RESERVED', 'All rights reserved')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='displayname',
            field=models.CharField(default=None, max_length=255, verbose_name='Display Name'),
        ),
    ]
