# Generated by Django 5.1.8 on 2025-06-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0012_alter_asset_license_alter_assetowner_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
