# Generated by Django 5.1.8 on 2025-06-17 01:11

from django.db import migrations


def forward(apps, schema_editor):
    Format = apps.get_model("icosa", "Format")
    formats = Format.objects.filter(format_type="GLTF")
    formats.update(format_type="GLTF1")


def back(apps, schema_editor):
    Format = apps.get_model("icosa", "Format")
    formats = Format.objects.filter(format_type="GLTF1")
    formats.update(format_type="GLTF")


class Migration(migrations.Migration):
    dependencies = [
        ("icosa", "0013_alter_format_role"),
    ]

    operations = [
        migrations.RunPython(forward, back),
    ]
