# Generated by Django 5.1.8 on 2025-06-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0014_auto_20250617_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='format',
            old_name='is_preferred_for_viewer',
            new_name='is_preferred_for_gallery_viewer',
        ),
        migrations.RemoveField(
            model_name='format',
            name='is_preferred_for_download',
        ),
        migrations.AddField(
            model_name='format',
            name='hide_from_downloads',
            field=models.BooleanField(default=False),
        ),
    ]
