# Generated by Django 5.0.6 on 2024-06-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("icosa", "0014_alter_asset_orienting_rotation"),
    ]

    operations = [
        migrations.RunSQL(
            sql="\n            DROP VIEW IF EXISTS public.expandedassets;\n            ",
            reverse_sql="\n            CREATE VIEW public.expandedassets AS\n            SELECT assets.id,\n            assets.url,\n            assets.name,\n            assets.owner,\n            users.displayname AS ownername,\n            users.url AS ownerurl,\n            assets.formats,\n            assets.description,\n            assets.visibility,\n            assets.curated,\n            assets.polyid,\n            assets.polydata,\n            assets.thumbnail\n            FROM (public.assets\n            LEFT JOIN public.users ON ((assets.owner = users.id)));\n            ",
        ),
    ]
