# Generated by Django 5.1.8 on 2025-06-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0015_rename_is_preferred_for_viewer_format_is_preferred_for_gallery_viewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='hide_from_downloads',
            field=models.BooleanField(default=False),
        ),
    ]
