# Generated by Django 5.0.6 on 2024-06-27 10:16

import django.db.models.deletion
import icosa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0016_alter_asset_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=icosa.models.thumbnail_upload_path),
        ),
        migrations.CreateModel(
            name='IcosaFormat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to=icosa.models.format_upload_path)),
                ('format', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icosa.asset')),
                ('subfiles', models.ManyToManyField(blank=True, related_name='parent_files', to='icosa.icosaformat')),
            ],
        ),
    ]
