# Generated by Django 5.1.8 on 2025-07-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0016_resource_hide_from_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatRoleLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_text', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=1024)),
            ],
        ),
    ]
