# Generated by Django 5.0.6 on 2024-06-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0017_alter_asset_thumbnail_icosaformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='icosaformat',
            name='is_mainfile',
            field=models.BooleanField(default=False),
        ),
    ]
