# Generated by Django 5.1.8 on 2025-07-15 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0017_formatrolelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatrolelabel',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formatrolelabel',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
