# Generated by Django 5.1.8 on 2025-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0018_formatrolelabel_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
