# Generated by Django 5.0.6 on 2024-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0018_icosaformat_is_mainfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
