# Generated by Django 5.0.6 on 2024-07-04 16:30

import django.db.models.deletion
import icosa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0019_asset_imported'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolyFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icosa.asset')),
            ],
        ),
        migrations.CreateModel(
            name='PolyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('file', models.FileField(max_length=255, upload_to=icosa.models.format_upload_path)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icosa.polyformat')),
            ],
        ),
    ]
