# Generated by Django 5.1.8 on 2025-10-08 10:47

import django.core.validators
import django.db.models.deletion
import icosa.models.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0019_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=1024, null=True, upload_to=icosa.models.helpers.collection_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted'), ('ARCHIVED', 'Archived')], db_default='PRIVATE', default='PRIVATE', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCollectionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icosa.asset')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_assets', to='icosa.assetcollection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='assets',
            field=models.ManyToManyField(blank=True, null=True, through='icosa.AssetCollectionAsset', to='icosa.asset'),
        ),
    ]
