# Generated by Django 5.1.8 on 2025-10-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0020_assetcollection_assetcollectionasset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
