# Generated by Django 5.1.8 on 2025-10-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0021_alter_asset_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcollection',
            name='assets',
            field=models.ManyToManyField(blank=True, through='icosa.AssetCollectionAsset', to='icosa.asset'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
