# Generated by Django 5.0.6 on 2024-07-08 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0021_remove_polyformat_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triangle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('lod_hint', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icosa.polyformat')),
            ],
        ),
    ]
