# Generated by Django 5.0.6 on 2024-07-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0022_formatcomplexity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IcosaFormat',
        ),
    ]
