# Generated by Django 5.1.8 on 2025-10-22 19:15

from django.db import migrations
from django.db.models import Case, Value, When


def flip(apps, schema_editor):
    Format = apps.get_model("icosa", "Format")
    Format.objects.all().update(
        hide_from_downloads=Case(When(hide_from_downloads=True, then=Value(False)), default=Value(True))
    )


def forward(apps, schema_editor):
    flip(apps, schema_editor)


def back(apps, schema_editor):
    flip(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ("icosa", "0022_alter_assetcollection_assets_and_more"),
    ]

    operations = [migrations.RunPython(forward, back)]
