# Generated by Django 5.1.8 on 2025-10-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0023_flip_format_hide_from_downloads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='format',
            old_name='hide_from_downloads',
            new_name='is_preferred_for_download',
        ),
    ]
