# Generated by Django 5.1.8 on 2025-10-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0024_rename_hide_from_downloads_format_is_preferred_for_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='is_preferred_for_download',
            field=models.BooleanField(default=True),
        ),
    ]
