# Generated by Django 5.0.6 on 2024-07-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0024_orientingrotation_remove_asset_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyresource',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
