# Generated by Django 5.1.14 on 2025-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0025_alter_format_is_preferred_for_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='has_vox',
            field=models.BooleanField(default=False),
        ),
    ]
