# Generated by Django 5.0.6 on 2024-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0026_polyresource_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyresource',
            name='contenttype',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
