# Generated by Django 5.1.14 on 2025-11-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0026_asset_has_vox'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['has_tilt', 'has_blocks', 'has_gltf1', 'has_gltf2', 'has_gltf_any', 'has_fbx', 'has_obj', 'has_vox'], name='icosa_asset_has_til_3bc9b6_idx'),
        ),
    ]
