# Generated by Django 5.0.6 on 2024-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0027_polyresource_contenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentationparams',
            options={'verbose_name': 'Presentation Params', 'verbose_name_plural': 'Presentation Params'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
