# Generated by Django 5.1.14 on 2025-11-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0027_asset_icosa_asset_has_til_3bc9b6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetowner',
            name='merged_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_owners', to='icosa.assetowner'),
        ),
    ]
