# Generated by Django 5.0.6 on 2024-07-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0028_alter_presentationparams_options_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='displayname',
            field=models.CharField(max_length=255, verbose_name='Display Name'),
        ),
    ]
