# Generated by Django 5.2.10 on 2026-02-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0028_alter_assetowner_merged_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uploaded_file_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
