# Generated by Django 5.2.10 on 2026-03-04 16:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('icosa', '0029_resource_uploaded_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('object_id', models.BigIntegerField()),
                ('state', models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='New', default='NEW', max_length=255)),
                ('data', models.JSONField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField()),
                ('recipients', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='moderation_changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='moderation_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='NEW', default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='moderation_state_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='moderation_state_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='raw_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='moderation_changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='moderation_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='NEW', default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='moderation_state_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='moderation_state_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetowner',
            name='moderation_changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='moderation_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='NEW', default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='moderation_state_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='moderation_state_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['moderation_state'], name='icosa_asset_moderat_2749b5_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcollection',
            index=models.Index(fields=['moderation_state'], name='icosa_asset_moderat_5cfbec_idx'),
        ),
        migrations.AddIndex(
            model_name='assetowner',
            index=models.Index(fields=['moderation_state'], name='icosa_asset_moderat_7a7427_idx'),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['content_type', 'object_id'], name='icosa_moder_content_65f3a9_idx'),
        ),
    ]
