# Generated by Django 5.2.10 on 2026-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0030_moderationevent_moderationnotification_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='format',
            name='icosa_forma_role_3f3cdd_idx',
        ),
        migrations.AlterField(
            model_name='asset',
            name='moderation_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='NEW', default='NEW', max_length=255),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='moderation_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='NEW', default='NEW', max_length=255),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='moderation_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='NEW', default='NEW', max_length=255),
        ),
        migrations.AlterField(
            model_name='moderationevent',
            name='state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='New', default='NEW', max_length=255),
        ),
        migrations.AddIndex(
            model_name='format',
            index=models.Index(fields=['role', 'is_preferred_for_gallery_viewer', 'is_preferred_for_download'], name='icosa_forma_role_2f2a15_idx'),
        ),
    ]
