# Generated by Django 5.2.10 on 2026-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0030_asset_moderation_state_moderationevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='moderation_state_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='data',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='New', default='NEW', max_length=255),
        ),
    ]
