# Generated by Django 5.2.10 on 2026-02-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0031_asset_moderation_state_change_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationevent',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
