# Generated by Django 5.0.6 on 2024-07-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0031_alter_userassetlike_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationparams',
            name='orienting_rotation',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='presentation_params',
        ),
        migrations.AddField(
            model_name='asset',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='color_space',
            field=models.CharField(choices=[('LINEAR', 'LINEAR'), ('GAMMA', 'GAMMA')], default='GAMMA', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='orienting_rotation_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='orienting_rotation_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='orienting_rotation_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='orienting_rotation_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrientingRotation',
        ),
        migrations.DeleteModel(
            name='PresentationParams',
        ),
    ]
