# Generated by Django 5.2.10 on 2026-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0031_remove_format_icosa_forma_role_3f3cdd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetowner',
            name='moderation_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
