# Generated by Django 5.2.10 on 2026-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0032_assetowner_moderation_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationevent',
            name='query_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
