# Generated by Django 5.2.10 on 2026-02-25 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0032_alter_moderationevent_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='moderation_state_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
