# Generated by Django 5.2.10 on 2026-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0033_moderationevent_query_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='previous_moderation_state',
            field=models.CharField(blank=True, choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='previous_moderation_state',
            field=models.CharField(blank=True, choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='previous_moderation_state',
            field=models.CharField(blank=True, choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], max_length=255, null=True),
        ),
    ]
