# Generated by Django 5.0.6 on 2024-07-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0033_asset_thumbnail_contenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polyresource',
            name='is_thumbnail',
        ),
    ]
