# Generated by Django 5.2.10 on 2026-02-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0033_asset_moderation_state_change_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='moderation_changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
