# Generated by Django 5.2.10 on 2026-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0034_asset_moderation_changed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='raw_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
