# Generated by Django 5.0.6 on 2024-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0034_remove_polyresource_is_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formatcomplexity',
            options={'verbose_name': 'Format Complexity Object', 'verbose_name_plural': 'Format Complexity Objects'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='formats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
