# Generated by Django 5.2.10 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icosa", "0034_asset_previous_moderation_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcollection",
            name="query_parameters",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
