# Generated by Django 5.2.10 on 2026-07-13 11:24

import django.core.validators
import django.db.models.deletion
import icosa.models.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0034_asset_previous_moderation_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetcollection',
            options={'verbose_name': 'Asset Collection', 'verbose_name_plural': 'Asset Collections'},
        ),
        migrations.AlterModelOptions(
            name='assetcollectionasset',
            options={'ordering': ('order',), 'verbose_name': 'Collection Asset', 'verbose_name_plural': 'Collection Assets'},
        ),
        migrations.AlterModelOptions(
            name='bulksavelog',
            options={'verbose_name': 'Bulk Save Log', 'verbose_name_plural': 'Bulk Save Logs'},
        ),
        migrations.AlterModelOptions(
            name='devicecode',
            options={'verbose_name': 'Device Code', 'verbose_name_plural': 'Device Codes'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Format', 'verbose_name_plural': 'Formats'},
        ),
        migrations.AlterModelOptions(
            name='formatrolelabel',
            options={'verbose_name': 'Format Role Label', 'verbose_name_plural': 'Format Role Labels'},
        ),
        migrations.AlterModelOptions(
            name='hiddenmediafilelog',
            options={'verbose_name': 'Hidden Media File Log', 'verbose_name_plural': 'Hidden Media File Logs'},
        ),
        migrations.AlterModelOptions(
            name='mastheadsection',
            options={'verbose_name': 'Masthead Section', 'verbose_name_plural': 'Masthead Sections'},
        ),
        migrations.AlterModelOptions(
            name='oauth2client',
            options={'verbose_name': 'OAuth2 Client', 'verbose_name_plural': 'OAuth2 Clients'},
        ),
        migrations.AlterModelOptions(
            name='oauth2code',
            options={'verbose_name': 'OAuth2 Authorization Code', 'verbose_name_plural': 'OAuth2 Authorization Codes'},
        ),
        migrations.AlterModelOptions(
            name='oauth2token',
            options={'verbose_name': 'OAuth2 Token', 'verbose_name_plural': 'OAuth2 Tokens'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userlike',
            options={'verbose_name': 'User Like', 'verbose_name_plural': 'User Likes'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='camera',
            field=models.JSONField(blank=True, help_text='Camera settings', null=True, verbose_name='Camera'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, choices=[('MISCELLANEOUS', 'Miscellaneous'), ('ANIMALS', 'Animals & Pets'), ('ARCHITECTURE', 'Architecture'), ('ART', 'Art'), ('CULTURE', 'Culture & Humanity'), ('EVENTS', 'Current Events'), ('FOOD', 'Food & Drink'), ('HISTORY', 'History'), ('HOME', 'Furniture & Home'), ('NATURE', 'Nature'), ('OBJECTS', 'Objects'), ('PEOPLE', 'People & Characters'), ('PLACES', 'Places & Scenes'), ('SCIENCE', 'Science'), ('SPORTS', 'Sports & Fitness'), ('TECH', 'Tools & Technology'), ('TRANSPORT', 'Transport'), ('TRAVEL', 'Travel & Leisure')], max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='create_time',
            field=models.DateTimeField(verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='curated',
            field=models.BooleanField(default=False, help_text='Whether this asset has been curated by administrators', verbose_name='Curated'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the asset', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='downloads',
            field=models.PositiveIntegerField(default=0, help_text='Number of downloads', verbose_name='Downloads'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='formats',
            field=models.JSONField(blank=True, help_text='Available file formats', null=True, verbose_name='Formats'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='has_blocks',
            field=models.BooleanField(default=False, verbose_name='Has Blocks Format'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='has_fbx',
            field=models.BooleanField(default=False, verbose_name='Has FBX Format'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='has_gltf1',
            field=models.BooleanField(default=False, verbose_name='Has GLTF 1 Format'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='has_gltf2',
            field=models.BooleanField(default=False, verbose_name='Has GLTF 2 Format'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='has_gltf_any',
            field=models.BooleanField(default=False, verbose_name='Has GLTF Format'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='has_obj',
            field=models.BooleanField(default=False, verbose_name='Has OBJ Format'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='has_tilt',
            field=models.BooleanField(default=False, verbose_name='Has Tilt Brush Format'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='has_vox',
            field=models.BooleanField(default=False, verbose_name='Has VOX Format'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='historical_likes',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes from previous system', verbose_name='Historical Likes'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='historical_views',
            field=models.PositiveIntegerField(default=0, help_text='Number of views from previous system', verbose_name='Historical Views'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='imported_from',
            field=models.CharField(blank=True, help_text='Source from which this asset was imported', max_length=255, null=True, verbose_name='Imported From'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_viewer_compatible',
            field=models.BooleanField(default=False, help_text='Whether this asset can be viewed in the 3D viewer', verbose_name='Viewer Compatible'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_liked_time',
            field=models.DateTimeField(blank=True, help_text='Time when this asset was last liked', null=True, verbose_name='Last Liked Time'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_reported_by',
            field=models.ForeignKey(blank=True, help_text='Last user who reported this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_assets', to=settings.AUTH_USER_MODEL, verbose_name='Last Reported By'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_reported_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Reported Time'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='license',
            field=models.CharField(blank=True, choices=[('', 'No license chosen'), ('CREATIVE_COMMONS_BY_3_0', 'CC BY Attribution 3.0 International'), ('CREATIVE_COMMONS_BY_ND_3_0', 'CC BY-ND Attribution-NoDerivatives 3.0 International'), ('CREATIVE_COMMONS_BY_4_0', 'CC BY Attribution 4.0 International'), ('CREATIVE_COMMONS_0', 'CC0 1.0 Universal'), ('ALL_RIGHTS_RESERVED', 'All rights reserved')], help_text='License under which this asset is shared', max_length=50, null=True, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes', verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Creator or owner of this asset', null=True, on_delete=django.db.models.deletion.CASCADE, to='icosa.assetowner', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='polydata',
            field=models.JSONField(blank=True, help_text='Original Google Poly metadata', null=True, verbose_name='Poly Data'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='polyid',
            field=models.CharField(blank=True, help_text='Original Google Poly ID', max_length=255, null=True, verbose_name='Poly ID'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='preferred_viewer_format_override',
            field=models.OneToOneField(blank=True, help_text='Manually set preferred format for the 3D viewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_format_override_for', to='icosa.format', verbose_name='Preferred Viewer Format Override'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='presentation_params',
            field=models.JSONField(blank=True, help_text='Parameters for how the asset should be displayed', null=True, verbose_name='Presentation Parameters'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Preview image for this asset', max_length=1024, null=True, upload_to=icosa.models.helpers.preview_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])], verbose_name='Preview Image'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rank',
            field=models.FloatField(default=0, help_text='Calculated ranking score for sorting', verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='raw_tags',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Tags'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='remix_ids',
            field=models.JSONField(blank=True, help_text='IDs of assets this is remixed from', null=True, verbose_name='Remix IDs'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='search_text',
            field=models.TextField(blank=True, help_text='Denormalized text for searching', null=True, verbose_name='Search Text'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.CharField(choices=[('BARE', 'Bare'), ('UPLOADING', 'Uploading'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], db_default='BARE', default='BARE', help_text='Current processing state of the asset', max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorizing this asset', to='icosa.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for this asset', max_length=1024, null=True, upload_to=icosa.models.helpers.thumbnail_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='thumbnail_contenttype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail Content Type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='transform',
            field=models.JSONField(blank=True, help_text='3D transformation data', null=True, verbose_name='Transform'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='triangle_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of triangles in the 3D model', verbose_name='Triangle Count'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.CharField(blank=True, help_text='Unique URL identifier for this asset', max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of views', verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted'), ('ARCHIVED', 'Archived')], db_default='PRIVATE', default='PRIVATE', help_text='Who can view this asset', max_length=255, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text='Assets included in this collection', through='icosa.AssetCollectionAsset', to='icosa.asset', verbose_name='Assets'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='description',
            field=models.TextField(blank=True, help_text='Collection description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for this collection', max_length=1024, null=True, upload_to=icosa.models.helpers.collection_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='name',
            field=models.CharField(help_text='Collection name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='url',
            field=models.CharField(help_text='Unique URL identifier for this collection', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='user',
            field=models.ForeignKey(help_text='Owner of this collection', on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted'), ('ARCHIVED', 'Archived')], db_default='PRIVATE', default='PRIVATE', help_text='Who can view this collection', max_length=255, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='assetcollectionasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icosa.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='assetcollectionasset',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_assets', to='icosa.assetcollection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='assetcollectionasset',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='assetcollectionasset',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in collection', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='description',
            field=models.TextField(blank=True, help_text='Creator profile description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='disable_profile',
            field=models.BooleanField(default=False, help_text='Whether the profile page is disabled', verbose_name='Disable Profile'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='displayname',
            field=models.CharField(default=None, help_text='Public display name shown to users', max_length=255, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='django_user',
            field=models.ForeignKey(blank=True, help_text='Associated Django user account', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Django User'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='email',
            field=models.EmailField(blank=True, help_text="Creator's email address", max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='imported',
            field=models.BooleanField(default=False, help_text='Whether this account was imported from Google Poly', verbose_name='Imported'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='is_claimed',
            field=models.BooleanField(default=True, help_text='Whether this account has been claimed by a user', verbose_name='Is Claimed'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='merged_with',
            field=models.ForeignKey(blank=True, help_text='Another asset owner this account was merged with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_owners', to='icosa.assetowner', verbose_name='Merged With'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='migrated',
            field=models.BooleanField(default=False, help_text='Whether this account was migrated from another system', verbose_name='Migrated'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='moderation_exempt',
            field=models.BooleanField(default=False, verbose_name='Moderation Exempt'),
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='url',
            field=models.CharField(help_text='Unique username or URL identifier for this creator', max_length=255, unique=True, verbose_name='User Name / URL'),
        ),
        migrations.AlterField(
            model_name='bulksavelog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bulksavelog',
            name='finish_status',
            field=models.CharField(blank=True, choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('KILLED', 'Killed'), ('RESUMED', 'Resumed')], help_text='Final status of the bulk save operation', max_length=9, null=True, verbose_name='Finish Status'),
        ),
        migrations.AlterField(
            model_name='bulksavelog',
            name='finish_time',
            field=models.DateTimeField(blank=True, help_text='When the bulk save operation finished', null=True, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='bulksavelog',
            name='kill_sig',
            field=models.BooleanField(default=False, help_text='Whether a kill signal was sent to stop this operation', verbose_name='Kill Signal'),
        ),
        migrations.AlterField(
            model_name='bulksavelog',
            name='last_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the last processed item', null=True, verbose_name='Last ID'),
        ),
        migrations.AlterField(
            model_name='bulksavelog',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='devicecode',
            name='devicecode',
            field=models.CharField(help_text='Short code for device authentication', max_length=6, verbose_name='Device Code'),
        ),
        migrations.AlterField(
            model_name='devicecode',
            name='expiry',
            field=models.DateTimeField(help_text='When this code expires', verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='devicecode',
            name='user',
            field=models.ForeignKey(help_text='User associated with this device code', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='format',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icosa.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='format',
            name='format_type',
            field=models.CharField(help_text='File format type (e.g., GLTF, OBJ, FBX)', max_length=255, verbose_name='Format Type'),
        ),
        migrations.AlterField(
            model_name='format',
            name='is_preferred_for_download',
            field=models.BooleanField(default=True, help_text='Whether this format should be offered for download', verbose_name='Preferred for Download'),
        ),
        migrations.AlterField(
            model_name='format',
            name='is_preferred_for_gallery_viewer',
            field=models.BooleanField(default=False, help_text='Whether this format should be used in the 3D viewer', verbose_name='Preferred for Gallery Viewer'),
        ),
        migrations.AlterField(
            model_name='format',
            name='lod_hint',
            field=models.PositiveIntegerField(blank=True, help_text='Level of detail hint', null=True, verbose_name='LOD Hint'),
        ),
        migrations.AlterField(
            model_name='format',
            name='role',
            field=models.CharField(blank=True, help_text='Role or purpose of this format', max_length=255, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='format',
            name='root_resource',
            field=models.ForeignKey(blank=True, help_text='Main resource file for this format', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_formats', to='icosa.resource', verbose_name='Root Resource'),
        ),
        migrations.AlterField(
            model_name='format',
            name='triangle_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of triangles in this format', null=True, verbose_name='Triangle Count'),
        ),
        migrations.AlterField(
            model_name='format',
            name='zip_archive_url',
            field=models.CharField(blank=True, help_text='URL to archived version of this format', max_length=1024, null=True, verbose_name='ZIP Archive URL'),
        ),
        migrations.AlterField(
            model_name='formatrolelabel',
            name='create_time',
            field=models.DateTimeField(verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='formatrolelabel',
            name='label',
            field=models.CharField(help_text='User-friendly label for this role', max_length=1024, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='formatrolelabel',
            name='role_text',
            field=models.CharField(help_text='Internal role identifier', max_length=255, verbose_name='Role Text'),
        ),
        migrations.AlterField(
            model_name='formatrolelabel',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='hiddenmediafilelog',
            name='deleted_from_source',
            field=models.BooleanField(default=False, help_text='Whether the file has been permanently deleted from storage', verbose_name='Deleted from Source'),
        ),
        migrations.AlterField(
            model_name='hiddenmediafilelog',
            name='file_name',
            field=models.CharField(help_text='Name of the hidden file', max_length=1024, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='hiddenmediafilelog',
            name='original_asset_id',
            field=models.BigIntegerField(help_text='ID of the asset this file belonged to', verbose_name='Original Asset ID'),
        ),
        migrations.AlterField(
            model_name='mastheadsection',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Featured asset for this masthead section', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icosa.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='mastheadsection',
            name='headline_text',
            field=models.CharField(blank=True, help_text="Text displayed in place of an asset's name.", max_length=1024, null=True, verbose_name='Headline Text'),
        ),
        migrations.AlterField(
            model_name='mastheadsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Background image for this masthead section', max_length=1024, null=True, upload_to=icosa.models.helpers.masthead_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mastheadsection',
            name='sub_text',
            field=models.CharField(blank=True, help_text="Text displayed in place of an asset's owner's name.", max_length=1024, null=True, verbose_name='Sub Text'),
        ),
        migrations.AlterField(
            model_name='mastheadsection',
            name='url',
            field=models.CharField(blank=True, help_text="URL to link to in place of an asset's viewer page.", max_length=1024, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='client_id',
            field=models.CharField(max_length=48, unique=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='client_id_issued_at',
            field=models.IntegerField(default=0, verbose_name='Client ID Issued At'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='client_metadata',
            field=models.TextField(blank=True, null=True, verbose_name='Client Metadata'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='client_secret',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='client_secret_expires_at',
            field=models.IntegerField(default=0, verbose_name='Client Secret Expires At'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='auth_time',
            field=models.IntegerField(verbose_name='Auth Time'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='client_id',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='code',
            field=models.CharField(max_length=120, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='code_challenge',
            field=models.TextField(blank=True, null=True, verbose_name='Code Challenge'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='code_challenge_method',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Code Challenge Method'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='nonce',
            field=models.TextField(blank=True, null=True, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='redirect_uri',
            field=models.TextField(blank=True, null=True, verbose_name='Redirect URI'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='response_type',
            field=models.TextField(blank=True, null=True, verbose_name='Response Type'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='scope',
            field=models.TextField(blank=True, null=True, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='oauth2code',
            name='user_id',
            field=models.BigIntegerField(verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=models.CharField(max_length=255, unique=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token_revoked_at',
            field=models.IntegerField(default=0, verbose_name='Access Token Revoked At'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='client_id',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='expires_in',
            field=models.IntegerField(default=0, verbose_name='Expires In'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='issued_at',
            field=models.IntegerField(verbose_name='Issued At'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Refresh Token'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token_revoked_at',
            field=models.IntegerField(default=0, verbose_name='Refresh Token Revoked At'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='scope',
            field=models.TextField(blank=True, null=True, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='token_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Token Type'),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icosa.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='contenttype',
            field=models.CharField(help_text='MIME type of this resource', max_length=255, null=True, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='external_url',
            field=models.CharField(blank=True, help_text='URL to external resource file', max_length=1024, null=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded file', max_length=1024, null=True, upload_to=icosa.models.helpers.format_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icosa.format', verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='hide_from_downloads',
            field=models.BooleanField(default=False, help_text='Whether this resource should be hidden from download lists', verbose_name='Hide from Downloads'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploaded_file_path',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Uploaded File Path'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Tag name for categorizing assets', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayname',
            field=models.CharField(help_text='Public display name', max_length=255, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='asset',
            field=models.ForeignKey(help_text='Asset that was liked', on_delete=django.db.models.deletion.CASCADE, to='icosa.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='date_liked',
            field=models.DateTimeField(auto_now_add=True, help_text='When the user liked this asset', verbose_name='Date Liked'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(help_text='User who liked the asset', on_delete=django.db.models.deletion.CASCADE, related_name='likedassets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
