# Generated by Django 5.2.10 on 2026-08-18 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0034_asset_previous_moderation_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcollection',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_collections', to='icosa.assetowner'),
        ),
        migrations.AlterField(
            model_name='assetcollection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
