# Generated by Django 5.0.6 on 2024-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0035_alter_formatcomplexity_options_alter_asset_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='search_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
