# Generated by Django 5.2.10 on 2026-02-26 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0035_asset_raw_tags_moderationevent_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
