# Generated by Django 5.0.6 on 2024-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0036_asset_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
