# Generated by Django 5.2.10 on 2026-08-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0036_auto_20260818_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcollection',
            name='user',
        ),
    ]
