# Generated by Django 5.2.10 on 2026-02-26 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0036_moderationevent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcollection',
            name='moderation_changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='moderation_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='New', default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='moderation_state_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='moderation_state_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='moderation_state_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
