# Generated by Django 5.2.10 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icosa", "0036_assetcollection_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcollection",
            name="markdown",
            field=models.BooleanField(
                default=False,
                help_text="Render the collection description as Markdown.",
            ),
        ),
    ]
