# Generated by Django 5.2.10 on 2026-08-21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icosa", "0037_remove_assetcollection_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="url",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[django.core.validators.validate_slug],
            ),
        ),
    ]
