# Generated by Django 5.2.10 on 2026-08-21 12:05

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0037_remove_assetcollection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
