# Generated by Django 5.2.10 on 2026-02-26 16:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0037_assetcollection_moderation_changed_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetowner',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetowner',
            name='moderation_changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='moderation_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUERIED', 'Queried'), ('REPORTED', 'Reported'), ('MODIFIED', 'Modified')], db_default='New', default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='moderation_state_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='moderation_state_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetowner',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
