# Generated by Django 5.2.10 on 2026-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0038_assetowner_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField()),
                ('recipients', models.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['moderation_state'], name='icosa_asset_moderat_2749b5_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcollection',
            index=models.Index(fields=['moderation_state'], name='icosa_asset_moderat_5cfbec_idx'),
        ),
        migrations.AddIndex(
            model_name='assetowner',
            index=models.Index(fields=['moderation_state'], name='icosa_asset_moderat_7a7427_idx'),
        ),
    ]
