# Generated by Django 5.2.10 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icosa", "0038_create_featured_dynamic_collections"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_listing",
                        to="icosa.assetcollection",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "pk"),
            },
        ),
    ]
