# Generated by Django 5.2.10 on 2026-08-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0038_alter_asset_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcollection',
            name='query_parameters',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
