# Generated by Django 5.2.10 on 2026-08-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0038_alter_asset_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcollection',
            name='markdown',
            field=models.BooleanField(default=False, help_text='Render the collection description as Markdown.'),
        ),
        migrations.AddField(
            model_name='assetcollection',
            name='query_parameters',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_listing', to='icosa.assetcollection')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
    ]
