# Generated by Django 5.2.10 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("icosa", "0039_featuredcollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredcollection",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
