# Generated by Django 5.0.6 on 2024-07-30 12:58

import icosa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0039_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyresource',
            name='file',
            field=models.FileField(max_length=1024, upload_to=icosa.models.format_upload_path),
        ),
    ]
