# Generated by Django 5.0.6 on 2024-08-06 13:41

import icosa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0040_alter_polyresource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyresource',
            name='external_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='polyresource',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=icosa.models.format_upload_path),
        ),
    ]
