# Generated by Django 5.0.6 on 2024-08-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0042_polyresource_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyformat',
            name='archive_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
