# Generated by Django 5.0.6 on 2024-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0043_polyformat_archive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyresource',
            name='triangleCount',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
