# Generated by Django 5.0.6 on 2024-08-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0044_polyresource_trianglecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='remix_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
