# Generated by Django 5.0.6 on 2024-08-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0045_asset_remix_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polyresource',
            old_name='triangleCount',
            new_name='triangle_count',
        ),
    ]
