# Generated by Django 5.0.6 on 2024-08-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0046_rename_trianglecount_polyresource_triangle_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polyresource',
            name='triangle_count',
        ),
    ]
