# Generated by Django 5.0.6 on 2024-08-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0047_remove_polyresource_triangle_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='curated',
            field=models.BooleanField(default=False),
        ),
    ]
