# Generated by Django 5.0.6 on 2024-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0048_alter_asset_curated'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
