# Generated by Django 5.0.6 on 2024-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0051_rename_is_valid_asset_is_viewer_compatible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polyresource',
            name='role',
        ),
        migrations.AddField(
            model_name='polyformat',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'Original OBJ File'), (2, 'Tilt File'), (4, 'Unknown GLTF File'), (6, 'Original FBX File'), (7, 'Blocks File'), (8, 'USD File'), (11, 'HTML File'), (12, 'Original glTF File'), (13, 'Tour Creator Experience'), (15, 'JSON File'), (16, 'lullmodel File'), (17, 'sand File'), (18, 'GLB File'), (19, 'sand File'), (20, 'sandc File'), (21, 'pb File'), (22, 'Unknown GLTF File'), (24, 'Original Triangulated OBJ File'), (25, 'JPG (Buggy)'), (26, 'USDZ File'), (30, 'Updated glTF File'), (32, 'Editor settings pb file'), (35, 'Unknown GLTF File'), (36, 'Unknown GLB File'), (38, 'Unknown GLB File'), (39, 'Polygone GLTF File')], max_length=255, null=True),
        ),
    ]
