# Generated by Django 5.0.6 on 2024-09-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0053_asset_category_asset_downloads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
