# Generated by Django 5.0.6 on 2024-09-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0055_user_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyformat',
            name='lod_hint',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polyformat',
            name='triangle_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FormatComplexity',
        ),
    ]
