# Generated by Django 5.0.6 on 2024-09-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0058_alter_polyformat_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_viewer_compatible', 'visibility'], name='assets_is_view_1962a9_idx'),
        ),
    ]
