# Generated by Django 5.0.6 on 2024-09-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0059_alter_tag_options_asset_assets_is_view_1962a9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='has_blocks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_gltf1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_gltf2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_gltf_any',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_tilt',
            field=models.BooleanField(default=False),
        ),
    ]
