# Generated by Django 5.0.6 on 2024-09-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0060_asset_has_blocks_asset_has_gltf1_asset_has_gltf2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='has_fbx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_obj',
            field=models.BooleanField(default=False),
        ),
    ]
