# Generated by Django 5.0.6 on 2024-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0061_asset_has_fbx_asset_has_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
