# Generated by Django 5.0.6 on 2024-10-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0063_alter_asset_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='license',
            field=models.CharField(blank=True, choices=[('CREATIVE_COMMONS_BY', 'CC BY'), ('CREATIVE_COMMONS_BY-SA', 'CC BY-SA'), ('CREATIVE_COMMONS_BY-NC', 'CC BY-NC'), ('CREATIVE_COMMONS_BY-NC-SA', 'CC BY-NC-SA'), ('CREATIVE_COMMONS_BY-ND', 'CC BY-ND'), ('CREATIVE_COMMONS_BY-NC-ND', 'CC BY-NC-ND')], max_length=50, null=True),
        ),
    ]
