# Generated by Django 5.0.6 on 2024-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0065_alter_asset_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='license',
            field=models.CharField(blank=True, choices=[('', 'Please choose'), ('CREATIVE_COMMONS_0', 'CC0 1.0 Universal'), ('CREATIVE_COMMONS_BY_3_0', 'CC BY 3.0 Attribution 4.0 International'), ('CREATIVE_COMMONS_BY_ND_3_0', 'CC BY-ND Attribution-NoDerivatives 3.0 International'), ('CREATIVE_COMMONS_BY_4_0', 'CC BY 4.0 Attribution 4.0 International'), ('CREATIVE_COMMONS_BY_ND_4_0', 'CC BY-ND Attribution-NoDerivatives 4.0 International'), ('ALL_RIGHTS_RESERVED', 'All rights reserved')], max_length=50, null=True),
        ),
    ]
