# Generated by Django 5.0.6 on 2024-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0066_alter_asset_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='camera_transform',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='transform',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
