# Generated by Django 5.0.6 on 2024-10-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0067_asset_camera_transform_asset_transform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='camera_transform',
            new_name='camera',
        ),
    ]
