# Generated by Django 5.0.6 on 2024-11-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0072_alter_polyformat_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='color_space',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='orienting_rotation_w',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='orienting_rotation_x',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='orienting_rotation_y',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='orienting_rotation_z',
        ),
        migrations.AddField(
            model_name='asset',
            name='presentation_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
