# Generated by Django 5.0.6 on 2024-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0073_remove_asset_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='imported',
        ),
        migrations.AddField(
            model_name='asset',
            name='imported_from',
            field=models.CharField(blank=True, null=True),
        ),
    ]
