# Generated by Django 5.0.6 on 2024-11-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0074_remove_asset_imported_asset_imported_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_assets', to='icosa.user'),
        ),
        migrations.AddField(
            model_name='asset',
            name='reported_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
