# Generated by Django 5.0.6 on 2024-11-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0075_asset_reported_by_asset_reported_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='reported_by',
            new_name='last_reported_by',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='reported_time',
            new_name='last_reported_time',
        ),
    ]
