# Generated by Django 5.0.6 on 2024-11-06 13:08

import icosa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0077_alter_asset_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenMediaFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_asset_id', models.BigIntegerField()),
                ('file_name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=icosa.models.thumbnail_upload_path),
        ),
    ]
