# Generated by Django 5.0.6 on 2024-11-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0078_hiddenmediafilelog_alter_asset_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddenmediafilelog',
            name='deleted_from_source',
            field=models.BooleanField(default=False),
        ),
    ]
