# Generated by Django 5.0.6 on 2024-11-28 15:37

import icosa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0081_alter_asset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='preview_image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=icosa.models.thumbnail_upload_path),
        ),
    ]
