# Generated by Django 5.0.6 on 2024-12-19 13:49

import icosa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0086_mastheadsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='imported_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='preview_image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=icosa.models.preview_image_upload_path),
        ),
        migrations.AlterField(
            model_name='asset',
            name='thumbnail_contenttype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mastheadsection',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=icosa.models.masthead_image_upload_path),
        ),
    ]
