# Generated by Django 5.0.6 on 2025-01-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0087_alter_asset_imported_from_alter_asset_preview_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AssetOwner',
        ),
    ]
