# Generated by Django 5.0.6 on 2025-01-20 16:16

from django.db import migrations


def forward(apps, schema_editor):
    AssetOwner = apps.get_model("icosa", "AssetOwner")
    DjangoUser = apps.get_model("auth", "User")
    for django_user in DjangoUser.objects.all():
        try:
            asset_owner = AssetOwner.objects.get(email=django_user.email)
            asset_owner.django_user = django_user
            asset_owner.save()
        except AssetOwner.DoesNotExist:
            pass


def backward(apps, schema_editor):
    AssetOwner = apps.get_model("icosa", "AssetOwner")
    AssetOwner.objects.all().update({"django_user": None})


class Migration(migrations.Migration):
    dependencies = [
        ("icosa", "0090_assetowner_django_user"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
