# Generated by Django 5.0.6 on 2025-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0092_assetowner_merged_with_alter_assetowner_django_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyformat',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'ORIGINAL_OBJ_FORMAT'), (2, 'TILT_FORMAT'), (4, 'UNKNOWN_GLTF_FORMAT_A'), (6, 'ORIGINAL_FBX_FORMAT'), (7, 'BLOCKS_FORMAT'), (8, 'USD_FORMAT'), (11, 'HTML_FORMAT'), (12, 'ORIGINAL_GLTF_FORMAT'), (13, 'TOUR_CREATOR_EXPERIENCE'), (15, 'JSON_FORMAT'), (16, 'LULLMODEL_FORMAT'), (17, 'SAND_FORMAT_A'), (18, 'GLB_FORMAT'), (19, 'SAND_FORMAT_B'), (20, 'SANDC_FORMAT'), (21, 'PB_FORMAT'), (22, 'UNKNOWN_GLTF_FORMAT_B'), (24, 'ORIGINAL_TRIANGULATED_OBJ_FORMAT'), (25, 'JPG_BUGGY'), (26, 'USDZ_FORMAT'), (30, 'UPDATED_GLTF_FORMAT'), (32, 'EDITOR_SETTINGS_PB_FORMAT'), (35, 'UNKNOWN_GLTF_FORMAT_C'), (36, 'UNKNOWN_GLB_FORMAT_A'), (38, 'UNKNOWN_GLB_FORMAT_B'), (39, 'TILT_NATIVE_GLTF'), (40, 'USER_SUPPLIED_GLTF'), (1000, 'POLYGONE_TILT_FORMAT'), (1001, 'POLYGONE_BLOCKS_FORMAT'), (1002, 'POLYGONE_GLB_FORMAT'), (1003, 'POLYGONE_GLTF_FORMAT'), (1004, 'POLYGONE_OBJ_FORMAT'), (1005, 'POLYGONE_FBX_FORMAT')], null=True),
        ),
    ]
