# Generated by Django 5.0.6 on 2025-02-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0093_alter_polyformat_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyformat',
            name='root_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icosa.polyresource'),
        ),
    ]
