# Generated by Django 5.0.6 on 2025-02-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0094_polyformat_root_resource'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='polyformat',
            index=models.Index(fields=['role'], name='icosa_polyf_role_dfebdb_idx'),
        ),
    ]
