# Generated by Django 5.0.6 on 2025-02-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0095_polyformat_icosa_polyf_role_dfebdb_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolyResource',
            new_name='Resource',
        ),
    ]
