# Generated by Django 5.0.6 on 2025-02-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0098_alter_polyformat_root_resource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolyFormat',
            new_name='Format',
        ),
        migrations.RenameIndex(
            model_name='format',
            new_name='icosa_forma_role_3f3cdd_idx',
            old_name='icosa_polyf_role_dfebdb_idx',
        ),
    ]
