# Generated by Django 5.0.6 on 2025-02-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0099_rename_polyformat_format_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['likes'], name='assets_likes_df6e36_idx'),
        ),
    ]
