# Generated by Django 5.0.6 on 2025-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0102_asset_assets_is_view_db625e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_liked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
