# Generated by Django 5.0.6 on 2025-02-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0103_asset_last_liked_time'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='icosa_asset_is_view_0ae61f_idx',
            old_name='assets_is_view_1962a9_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='icosa_asset_likes_301593_idx',
            old_name='assets_likes_df6e36_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='icosa_asset_owner_i_e76513_idx',
            old_name='assets_owner_i_b9eeda_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='icosa_asset_is_view_9b8d35_idx',
            old_name='assets_is_view_db625e_idx',
        ),
        migrations.AlterModelTable(
            name='asset',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assetowner',
            table=None,
        ),
        migrations.AlterModelTable(
            name='devicecode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='oauth2client',
            table=None,
        ),
        migrations.AlterModelTable(
            name='oauth2code',
            table=None,
        ),
        migrations.AlterModelTable(
            name='oauth2token',
            table=None,
        ),
    ]
