# Generated by Django 5.0.6 on 2025-02-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0106_remove_resource_is_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='is_preferred_for_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='format',
            name='is_preferred_for_viewer',
            field=models.BooleanField(default=False),
        ),
    ]
