# Generated by Django 5.0.6 on 2025-03-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0108_waitlistentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'ordering': ('-create_time',), 'verbose_name_plural': 'Waitlist entries'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
