# Generated by Django 5.0.6 on 2025-03-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0109_alter_waitlistentry_options_alter_asset_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSaveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('finish_status', models.CharField(blank=True, choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('KILLED', 'Killed')], max_length=9, null=True)),
                ('kill_sig', models.BooleanField(default=False)),
                ('last_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
