# Generated by Django 5.0.6 on 2025-03-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0110_bulksavelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksavelog',
            name='finish_status',
            field=models.CharField(blank=True, choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('KILLED', 'Killed'), ('RESUMED', 'Resumed')], max_length=9, null=True),
        ),
    ]
