# Generated by Django 5.0.6 on 2025-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0112_delete_waitlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
