# Generated by Django 5.0.6 on 2025-03-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0113_alter_asset_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='format',
            old_name='archive_url',
            new_name='zip_archive_url',
        ),
    ]
