# Generated by Django 5.0.6 on 2025-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icosa', '0116_assetowner_disable_profile_alter_asset_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted'), ('ARCHIVED', 'Archived')], db_default='PRIVATE', default='PRIVATE', max_length=255),
        ),
    ]
